### ISSUE TITLE
No module named 'pipelines.OmsIndependentDiffusionPipeline'

### ISSUE THREAD

**Issue by Skwarson96** [ShineChen1024/MagicClothing#69]
Hello!
I tried to run gradio_generate.py and I encountered error: 
Traceback (most recent call last):
  File "/home/user/MagicClothing/gradio_generate.py", line 9, in <module>
    from pipelines.OmsIndependentDiffusionPipeline import OmsIndependentDiffusionPipeline
ModuleNotFoundError: No module named 'pipelines.OmsIndependentDiffusionPipeline'

I see you don't have OmsIndependentDiffusionPipeline.py in pipelines directory

**Comment by ShineChen1024** [comment]
fixed!

**Comment by frankchieng** [comment]
> fixed!

i can't find the OmsIndependentDiffusionPipeline.py under the pipelines directory,i think the problem is still exist
